/**
 * 
 */
package com.bbva.net.back.model.enums;

/**
 * Enum of renders
 * 
 * @author User
 */
public enum RenderAttributes {

	/*
	 * GP12834 Cheques y chequeras - Entelgy - inicio
	 */

	RADIOSTATUS, NUMBERBOOK, NUMBERCHECK, STATUS, BUTTONBOOK, CALENDAR, CALENDARCHECK, BUTTONDATECHECK, BUTTONDATE, BUTTONBALANCE, BALANCEFILTER, INCOMEOREXPENSESFILTER, MOVEMENTSFILTER, FILTERDATE, FILTERDATECHECK, FILTERCHECKBOOK, FILTERNUMBERCHECK, FILTERSTATUS, MOVEMENTSTABLE, CHECKTABLE, CHECKBOOKTABLE, FOOTERTABLEMOVEMENT, FOOTERTABLECHEKS, FOOTERTABLECHEKBOOKS, TITLECHECKBOOKS, TITLECHECKS, TITLEMOVES, FOOTERTABLEQUOTA, FOOTERTABLECHECKBOOK;

	/*
	 * GP12834 Cheques y chequeras - Entelgy - fin
	 */

}
