/**
 *
 */
package com.bbva.net.back.model.enums;

/**
 * Enum of renders
 *
 * @author User
 */
public enum RenderAttributes {

    RADIOSTATUS, NUMBERBOOK, NUMBERCHECK, STATUS, BUTTONBOOK, CALENDAR, CALENDARCHECK, BUTTONDATECHECK, BUTTONDATE, BUTTONBALANCE, BALANCEFILTER, INCOMEOREXPENSESFILTER, MOVEMENTSFILTER, FILTERDATE, FILTERDATECHECK, FILTERCHECKBOOK, FILTERNUMBERCHECK, FILTERSTATUS, MOVEMENTSTABLE, CHECKTABLE, CHECKBOOKTABLE, FOOTERTABLEMOVEMENT, FOOTERTABLECHEKS, FOOTERTABLECHEKBOOKS, TITLECHECKBOOKS, TITLECHECKS, TITLEMOVES, FOOTERTABLEQUOTA, FOOTERTABLECHECKBOOK, CALENDAROUT, TITLEDIVISAINI, DIVISAINITABLE, TITLEMOUTSIDE, TITLEMRECIVED, OUTSIDETABLE, RECIVEDTABLE, FOOTEROUTSIDE, FOOTERRECIVED;

}
