/**
 * 
 */
package com.bbva.net.back.model.enums;

/**
 * Enum of renders
 * 
 * @author User
 */
public enum RenderAttributes {

	NUMBERBOOK(), NUMBERCHECK(),STATUS(), BUTTONBOOK(), CALENDAR(), BUTTONDATE(), BUTTONBALANCE(),BALANCEFILTER(),INCOMEOREXPENSESFILTER(),MOVEMENTSFILTER(), FILTERDATE(), FILTERCHECKBOOK(),FILTERNUMBERCHECK(), FILTERSTATUS(), MOVEMENTSTABLE(), CHECKTABLE(), FOOTERTABLEMOVEMENT(), FOOTERTABLECHEKS();

}
